### ISSUE TITLE
Artwork license question

### ISSUE THREAD

**Issue by falkTX** [mhampton/ZetaCarinaeModules#8]
Just a quick question, as I don't see it mentioned anywhere.
Your project is licensed under GPL-3.0-or-later, but does that include the graphics too? Or are those supposed to be in a different license?
Thanks!

**Comment by mhampton** [comment]
Hi,

I haven't thought that much about my graphics, since they aren't very good, but I intended that my module graphics would also be included under the GPL.  The only exception is in the documentation on github, I'll try to clarify that soon, the illustrations accompanying each module description were done by someone else and they retain the rights to those.

**Comment by falkTX** [comment]
I think the panels look quite fine, compared to mine yours are super nice :sweat_smile: 
GPL for artwork is quite fine, I was just not used to seeing that, but seems quite a few people from the Rack scene just go with reusing the code license for the artwork too, that's cool.

I will close this ticket then since it has been answered, thanks!
